baseurl: https://joonjeong.github.io/
languageCode: en-us
title: Dongseob Park, Joonjeong
theme: noteworthy
paginate: 5

# googleAnalytics: 

enableRobotsTXT: true
buildDrafts: false
buildFeature: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  email: dongseob.park@gmail.com
  twitter: https://twitter.com/joonjeong_kr
  utterances:
    github_repo: joonjeong/joonjeong.github.io
    github_label: utterances
    theme: github-light
